export default defineAppConfig({
  features: {
    ARCHWAY_ECOSYSTEM: false,
    ARCHWAY_CONNECT: false,
  },
  externalLinks: {
    ARCHWAY_TECHNICAL_OVERVIEW: 'https://archway.io/technology',
    ARCHWAY_TECHNICAL_PAPERS: 'https://archway.io/whitepapers',
    ARCHWAY_ECOSYSTEM: 'https://archway.io/ecosystem',
    ARCHWAY_COMMUNITY_HUB: 'https://archway.io/community',
    ARCHWAY_NEWSLETTER: 'https://archway.io/newsletter',
    ARCHWAY_BRAND: 'https://archway.io/brand',
    ARCHWAY_PRIVACY: 'https://archway.io/privacy',
    ARCHWAY_TERMS: 'https://archway.io/terms',
    ARCHWAY_GRANTS: 'https://archway.io/grants',
    ARCHWAY_REWARDS: 'https://rewards.archway.io',
    ARCHWAY_DOCS: '',
    ARCHWAY_CONNECT: 'https://test.connect.archway.io',
    ARCHWAY_STATUS: 'https://archway-network.statuspage.io',
    ARCHWAY_BLOG: 'https://blog.archway.io',
    ARCHWAY_GOT_DAPP_IDEA_FORM: 'https://docs.google.com/forms/d/e/1FAIpQLSfJL3E12uD0kmivVHF4Naxab7DR4CYdYKXf7ouQJznOlmUn9Q/viewform',
    ARCHWAY_PARTNERSHIPS_FORM: 'https://docs.google.com/forms/d/1MC6B-QwaPyyGuLMZWw270PDx63JdLXLJMeFKuhvlFrk/viewform',
    ARCHWAY_GOVERNANCE_FORUM: 'https://gov.archway.io',
    ARCH3JS_REPO: 'https://github.com/archway-network/arch3.js',
    ARCHWAY_CLI_REPO: 'https://github.com/archway-network/archway-cli',
    AREA_52: 'https://area-52.io',
    DISCORD: 'https://discord.gg/5FVvx3WGfa',
    TELEGRAM: 'https://t.me/archway_hq',
    TWITTER: 'https://twitter.com/archwayhq',
    YOUTUBE: 'https://www.youtube.com/@ArchwayNetwork',
    GITHUB: 'https://github.com/archway-network',
    REDDIT: 'https://www.reddit.com/r/Archway',
  },
});
