services:
  app:
    image: archwaynetwork/docs:development
    build:
      context: .
      target: development
    command: npm run dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
    driver: local
