/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.



Available document ids are:
- node/configure
- node/install
- node/join-a-network
- node/running-a-local-testnet
- participate/contribute
- participate/staking
- participate/wallet
- validator/monitoring-validators
- validator/overview
- validator/requirements
- validator/running-a-validator-node
- validator/troubleshooting

 */

module.exports = {
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
  pageSidebar: [
    {
      type: 'category',
      collapsed: true,
      label: 'Overview',
      items: [
        {type: 'ref', id:'overview/about', href: 'docs/overview/about', label:'About'},
        {type: 'ref', id:'overview/network', href: 'docs/overview/network', label:'Networks'},
        {type: 'ref', id:'overview/join-the-community', href: 'docs/overview/join-the-community', label:'Join the Archway Community'},
        {type: 'ref', id:'overview/glossary', href: 'docs/overview/glossary', label:'Glossary'},
        {type: 'ref', id:'overview/faq', href: 'docs/overview/faq', label:'FAQ'}
      ]
    },
    { 
      type: 'category',
      collapsed: true,
      label: 'Developers',
      items: [
        {
          type: 'category',
          collapsed: true,
          label: 'Getting Started',
          items: [
            {type: 'ref', id:'create/getting-started/install', href: 'docs/create/getting-started/install', label:'Installation'},
            {type: 'ref', id:'create/getting-started/setup', href: 'docs/create/getting-started/setup', label:'Setup'},
            {type: 'ref', id:'create/getting-started/basics', href: 'docs/create/getting-started/basics', label:'Basics'},
          ]
        },
        {
          type: 'category',
          collapsed: true,
          label: 'Guides',
          items: [
            {type: 'ref', id:'create/guides/my-first-dapp/start', href: 'docs/create/guides/my-first-dapp/start', label:'Starting out'},
            {type: 'ref', id:'create/guides/my-first-dapp/faucet', href: 'docs/create/guides/my-first-dapp/faucet', label:'Requesting Testnet funds'},
            {type: 'ref', id:'create/guides/my-first-dapp/wasm', href: 'docs/create/guides/my-first-dapp/wasm', label:'Producing Wasm executables'},
            {type: 'ref', id:'create/guides/my-first-dapp/deploy', href: 'docs/create/guides/my-first-dapp/deploy', label:'Deploying your contract on chain'},
            {type: 'ref', id:'create/guides/my-first-dapp/interact', href: 'docs/create/guides/my-first-dapp/interact', label:'Interacting with your contract'},
            {type: 'ref', id:'create/guides/my-first-dapp/dapp', href: 'docs/create/guides/my-first-dapp/dapp', label:'Building a dApp frontend'}
          ]
        },
      ]
    }
  ]
};