apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: archway-docs
  name: archway-docs
  namespace: archway-docs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: archway-docs
  template:
    metadata:
      labels:
        app: archway-docs
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: IMAGE_VERSION
        imagePullPolicy: Always
        name: archway-docs
        resources: {}
        env:
        - name: ALGOLIA_SEARCH_API_KEY
          valueFrom:
            secretKeyRef:
              name: archway-docs
              key: ALGOLIA_SEARCH_API_KEY
        - name: ALGOLIA_WRITE_API_KEY
          valueFrom:
            secretKeyRef:
              name: archway-docs
              key: ALGOLIA_WRITE_API_KEY
        - name: ALGOLIA_APPLICATION_ID
          valueFrom:
            secretKeyRef:
              name: archway-docs
              key: ALGOLIA_APPLICATION_ID
        - name: ALGOLIA_INDEX
          valueFrom:
            secretKeyRef:
              name: archway-docs
              key: ALGOLIA_INDEX
        - name: ENV
          valueFrom:
            secretKeyRef:
              name: archway-docs
              key: ENV
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: archway-docs
  name: archway-docs
  namespace: archway-docs
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: archway-docs
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/name: archway-docs
  name: archway-docs
  namespace: archway-docs
spec:
  ingressClassName: nginx
  rules:
    - host: docs.archway.io
      http:
        paths:
          - backend:
              service:
                name: archway-docs
                port:
                  number: 3000
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - docs.archway.io
      secretName: archway-docs-cert
---
apiVersion: v1
kind: Secret
metadata:
  name: archway-docs
type: Opaque
data:
  ALGOLIA_SEARCH_API_KEY: ALGOLIA_SEARCH_API_KEY_B64
  ALGOLIA_WRITE_API_KEY: ALGOLIA_WRITE_API_KEY_B64
  ALGOLIA_APPLICATION_ID: ALGOLIA_APPLICATION_ID_B64
  ALGOLIA_INDEX: ALGOLIA_INDEX_B64
  ENV: ENV_B64
