name: Deploy Feature Preview

on: pull_request

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      environment: staging
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    environment: staging
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test outputs
        run: |
          echo "image-version=${{ needs.build.outputs.image-version }}"
          echo "image-tags=${{ needs.build.outputs.image-tags }}"

      # -v- Everything bellow shall be replaced with the Kubernetes deployment -v-

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          ALGOLIA_APPLICATION_ID: "${{ secrets.ALGOLIA_APPLICATION_ID }}"
          ALGOLIA_SEARCH_API_KEY: "${{ secrets.ALGOLIA_SEARCH_API_KEY }}"
          ALGOLIA_WRITE_API_KEY: "${{ secrets.ALGOLIA_WRITE_API_KEY }}"
          ALGOLIA_INDEX: "${{ secrets.ALGOLIA_INDEX }}"

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ARCHWAY_NETWORK_DOCS }}"
          expires: 7d
          projectId: archway-network-docs
