name: Build Docker image

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: string

    secrets:
      # DOCKER_USER_NAME:
      #   description: "DockerHub username"
      #   required: true
      # DOCKER_PASSWORD:
      #   description: "DockerHub password"
      #   required: true
      ALGOLIA_APPLICATION_ID:
        description: "Algolia Application ID"
        required: true
      ALGOLIA_SEARCH_API_KEY:
        description: "Algolia Search API Key"
        required: true
      ALGOLIA_WRITE_API_KEY:
        description: "Algolia Write/Admin API Key"
        required: true
      ALGOLIA_INDEX:
        description: "Algolia Index"
        required: true

    outputs:
      image-version:
        description: "Docker image version"
        value: ${{ jobs.build-docker-image.outputs.version }}
      image-tags:
        description: "Docker image tags"
        value: ${{ jobs.build-docker-image.outputs.tags }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      version: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Disabled for now, as we're not pushing to DockerHub
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USER_NAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: archwaynetwork/docs
          tags: |
            type=semver,pattern={{raw}}
            type=sha

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            ALGOLIA_APPLICATION_ID=${{ secrets.ALGOLIA_APPLICATION_ID }}
            ALGOLIA_SEARCH_API_KEY=${{ secrets.ALGOLIA_SEARCH_API_KEY }}
            ALGOLIA_WRITE_API_KEY=${{ secrets.ALGOLIA_WRITE_API_KEY }}
            ALGOLIA_INDEX=${{ secrets.ALGOLIA_INDEX }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
